In [1]:
import pandas as pd
import numpy as np

DETECTE MISSING VALUE

In [7]:
df = pd.DataFrame({'A':[4,5,6,np.nan],'B':[4,1,1,2],'C':[1]*4,'D': [2]*4})

In [8]:
df

A  B  C  D
0  4.0  4  1  2
1  5.0  1  1  2
2  6.0  1  1  2
3  NaN  2  1  2

In [10]:
df.nunique()

A    3
B    3
C    1
D    1
dtype: int64

In [5]:
df.nunique(axis=1)

0    3
1    3
2    3
3    2
dtype: int64

In [6]:
df.nunique().index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [7]:
to_del = [col for col in df.nunique().index if df.nunique()[col]==1]
to_del

['C', 'D']

In [8]:
df = df.drop(to_del,axis=1)
df

A  B
0  4.0  4
1  5.0  1
2  6.0  1
3  NaN  2

In [9]:
df

A  B
0  4.0  4
1  5.0  1
2  6.0  1
3  NaN  2

REMOVE COLUMN HAS LOW VARIANCE

In [11]:
df['C'] = [1,1,1,0]
df['D'] = [2,2,2,2]

In [15]:
df.var()

A    1.00
B    2.00
C    0.25
D    0.00
dtype: float64

In [13]:
def low_var(df,thresh):
    to_del = [col for col in df.var().index if df.var()[col]<=thresh]
    return to_del  

In [14]:
to_del = low_var(df,0.3)
to_del

['C', 'D']

In [15]:
from sklearn.feature_selection import VarianceThreshold
# define the transform
transform = VarianceThreshold(threshold = 0.3)
# transform the input data
X_sel = pd.DataFrame(transform.fit_transform(df),columns = list('AB'))
X_sel

A    B
0  4.0  4.0
1  5.0  1.0
2  6.0  1.0
3  NaN  2.0

REMOVING DUPLICATES

In [16]:
df = pd.DataFrame({'k1':['one','two']*3 + ['two'],'k2':[1,1,2,3,3,4,4]})
df

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [17]:
###The 'duplicated' method returns a boolean Series indicating whether each row is a duplicate or not
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [18]:
###drop_duplicates returns a DataFrame whte the duplicated array is False. By default keep the first observed value
df.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [19]:
df.drop_duplicates(keep='last')

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4

In [20]:
###To remove duplicates on specific columns, use subset
df.drop_duplicates(subset = ['k1'])

k1  k2
0  one   1
1  two   1

In [21]:
str_data = pd.Series(['a','b','c','d',np.nan,None])
str_data.isnull()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

Nan - missing data in pandas
None - the built-in Python value refering to missing data 

In [22]:
str_data.isnull().sum()###count the number of missing values in dataframe

2

FILTERING OUT MISSING DATA

In [23]:
str_data[~str_data.isnull()]

0    a
1    b
2    c
3    d
dtype: object

In [24]:
##using dropna
str_data.dropna()

0    a
1    b
2    c
3    d
dtype: object

In [3]:
import numpy as np
import pandas as pd

In [4]:
###using dropna for DataFrame objects
df = pd.DataFrame([[1.,6.5,3.,np.nan],[1,np.nan,np.nan,np.nan],\
                   [np.nan,np.nan,np.nan,np.nan],[np.nan,6.5,3.0,np.nan]])
df.columns = ['a','b','c','d']

In [26]:
df

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [27]:
df.isnull().sum()

a    2
b    2
c    2
d    4
dtype: int64

In [28]:
df.isnull().sum(axis=1)

0    1
1    3
2    4
3    2
dtype: int64

In [29]:
ser = df.isnull().sum()/df.shape[0]
list_drop_cols = ser[ser>=0.9].index
list_drop_cols

Index(['d'], dtype='object')

In [30]:
df.drop(list_drop_cols,axis=1)

a    b    c
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [31]:
ser = df.isnull().sum(axis=1)/df.shape[1]
list_drop_index = ser[ser>=0.9].index
list_drop_index
df.drop(list_drop_index,axis=0)

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [32]:
df.dropna(axis=1)###by default dropna drops any row containing a missing value

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [33]:
df.dropna(how = 'all')###drop rows that are all NA

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [34]:
df

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [35]:
df.dropna(axis=1,how='all')

a    b    c
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [36]:
###keep only rows containing a certain number of observations
df.dropna(thresh=2)

a    b    c   d
0  1.0  6.5  3.0 NaN
3  NaN  6.5  3.0 NaN

In [38]:
###modify original dataframe using inplace
df.dropna(how='all',inplace = True)

In [39]:
df

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

FILLING IN MISSING DATA ### fillna method

In [40]:
###can fill missing value with any number
df.fillna(0)

a    b    c    d
0  1.0  6.5  3.0  0.0
1  1.0  0.0  0.0  0.0
3  0.0  6.5  3.0  0.0

In [41]:
df.fillna(999)

a      b      c      d
0    1.0    6.5    3.0  999.0
1    1.0  999.0  999.0  999.0
3  999.0    6.5    3.0  999.0

In [42]:
###fillna with a dict, you can use a diffent fill value for each column. 
###Fill the missing value in the column a by 1, column b by 6.5
df.fillna({'a':1,'b':6.5})

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  6.5  NaN NaN
3  1.0  6.5  3.0 NaN

In [43]:
df

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [5]:
df2 = pd.DataFrame(np.arange(0,16,1).reshape(4,4), columns=list("abcd"))
df.fillna(df2)

a    b     c     d
0   1.0  6.5   3.0   3.0
1   1.0  5.0   6.0   7.0
2   8.0  9.0  10.0  11.0
3  12.0  6.5   3.0  15.0

In [45]:
###The interpolation methods can be used with fillna
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = np.nan
df.iloc[4:,2] = np.nan

In [46]:
df

0         1         2
0  1.241279  0.248244 -0.156691
1  0.224120  0.920960  0.448782
2 -0.290075       NaN -0.611516
3  1.207927       NaN  1.022667
4  0.893322       NaN       NaN
5 -0.150698       NaN       NaN

In [47]:
df.fillna(method='ffill')

0         1         2
0  1.241279  0.248244 -0.156691
1  0.224120  0.920960  0.448782
2 -0.290075  0.920960 -0.611516
3  1.207927  0.920960  1.022667
4  0.893322  0.920960  1.022667
5 -0.150698  0.920960  1.022667

In [48]:
df.fillna(method='ffill',limit =2) ###ffill ~ pad

0         1         2
0  1.241279  0.248244 -0.156691
1  0.224120  0.920960  0.448782
2 -0.290075  0.920960 -0.611516
3  1.207927  0.920960  1.022667
4  0.893322       NaN  1.022667
5 -0.150698       NaN  1.022667

In [49]:
df.fillna(method='bfill')

0         1         2
0  1.241279  0.248244 -0.156691
1  0.224120  0.920960  0.448782
2 -0.290075       NaN -0.611516
3  1.207927       NaN  1.022667
4  0.893322       NaN       NaN
5 -0.150698       NaN       NaN

In [50]:
df.iloc[4,1] = 2
df

0         1         2
0  1.241279  0.248244 -0.156691
1  0.224120  0.920960  0.448782
2 -0.290075       NaN -0.611516
3  1.207927       NaN  1.022667
4  0.893322  2.000000       NaN
5 -0.150698       NaN       NaN

In [51]:
df.fillna(method='bfill') ### bfill ~ backfill

0         1         2
0  1.241279  0.248244 -0.156691
1  0.224120  0.920960  0.448782
2 -0.290075  2.000000 -0.611516
3  1.207927  2.000000  1.022667
4  0.893322  2.000000       NaN
5 -0.150698       NaN       NaN

USE STATISTICAL IMPUTATION

In [52]:
df = pd.DataFrame([[1.,6.5,3.,np.nan],[1,np.nan,np.nan,np.nan],\
                   [np.nan,np.nan,np.nan,np.nan],[np.nan,6.5,3.0,np.nan]])
df.columns = ['a','b','c','d']

In [53]:
df

a    b    c   d
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [54]:
###Sklearn SimpleImputer with Mean
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy='mean')

mean_imputer.fit(df)

# pd.DataFrame(result_mean_imputer, columns=list('ABCD'))

SimpleImputer()

In [55]:
mean_imputer.statistics_

array([1. , 6.5, 3. , nan])

In [56]:
pd.DataFrame(mean_imputer.transform(df),columns = list('ABC'))

A    B    C
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [57]:
mean_imputer.fit_transform(df)

array([[1. , 6.5, 3. ],
       [1. , 6.5, 3. ],
       [1. , 6.5, 3. ],
       [1. , 6.5, 3. ]])

In [58]:
###Sklearn SimpleImputer with Constant
from sklearn.impute import SimpleImputer
constant_imputer = SimpleImputer(strategy='constant',fill_value = 99)

result_constant_imputer = constant_imputer.fit_transform(df)

pd.DataFrame(result_constant_imputer, columns=list('ABCD'))

A     B     C     D
0   1.0   6.5   3.0  99.0
1   1.0  99.0  99.0  99.0
2  99.0  99.0  99.0  99.0
3  99.0   6.5   3.0  99.0

In [59]:
most_fr_imputer = SimpleImputer(strategy='most_frequent')

result_most_fr_imputer = most_fr_imputer.fit_transform(df)

pd.DataFrame(result_most_fr_imputer, columns=list('ABC'))

A    B    C
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [60]:
df.loc[0,'a'] = 2

In [61]:
df

a    b    c   d
0  2.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [62]:
###. If there is more than one such value, only the smallest is return
most_fr_imputer = SimpleImputer(strategy='most_frequent')

result_most_fr_imputer = most_fr_imputer.fit_transform(df)

pd.DataFrame(result_most_fr_imputer, columns=list('ABC'))

A    B    C
0  2.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [63]:
df.fillna('?',inplace=True)

In [64]:
df = df.astype('str')

In [65]:
most_fr_imputer = SimpleImputer(strategy='most_frequent')

result_most_fr_imputer = most_fr_imputer.fit_transform(df)

pd.DataFrame(result_most_fr_imputer, columns=list('ABCD'))

A    B    C  D
0  2.0  6.5  3.0  ?
1  1.0    ?    ?  ?
2    ?    ?    ?  ?
3    ?  6.5  3.0  ?

Need pass missing_values = '?' into imputer

In [66]:
most_fr_imputer = SimpleImputer(strategy='most_frequent',missing_values='?')

result_most_fr_imputer = most_fr_imputer.fit_transform(df)

pd.DataFrame(result_most_fr_imputer, columns=list('ABC'))

A    B    C
0  2.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

KNN IMPUTATION

In [67]:
import numpy as np
from sklearn.impute import KNNImputer
X = pd.DataFrame([[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]])
imputer = KNNImputer(n_neighbors=2)
result = pd.DataFrame(imputer.fit_transform(X))

In [69]:
X

0  1    2
0  1.0  2  NaN
1  3.0  4  3.0
2  NaN  6  5.0
3  8.0  8  7.0

In [70]:
result

0    1    2
0  1.0  2.0  4.0
1  3.0  4.0  3.0
2  5.5  6.0  5.0
3  8.0  8.0  7.0

In [71]:
from numpy.random import randn

In [72]:
data = 5*randn(1000) + 50

In [73]:
mean = data.mean()
std = data.std()
cut_off = 3*std
lower, upper = mean - cut_off, mean + cut_off

In [74]:
outliers = [x for x in data if x<lower or x>upper]
outliers

[66.05203186056087,
 33.81316013344187,
 66.95063491310769,
 65.10067130290692,
 64.57443760320021]

In [75]:
outliers_removed = [x for x in data if ((x>=lower) and (x<=upper))]
len(outliers_removed)

995

In [76]:
import numpy as np
from sklearn.impute import KNNImputer
X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(X)


array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])

In [77]:
imputer.fit(X)

KNNImputer(n_neighbors=2)

In [78]:
from sklearn.metrics.pairwise import nan_euclidean_distances
l1 = [[3,None,None,6]]
l2 = [[1,None,4,5]]
print(nan_euclidean_distances(l1,l2))

[[3.16227766]]
